const nodes = [
  { id:'center', type:'center', x:385, y:300, w:150, h:72,
    title:'Kingdom of Heaven', sub:'Matthew 5–7' },

  { id:'cmd1', type:'cmd', x:20, y:88,  w:182, h:90,
    badge:'You shall not covet', title:'AI cheating culture',
    sub:'Wanting grades without the effort, using LLMs as shortcuts',
    detail:{ label:'Commandment — Guardrail',
      body:`Since the introduction of AI, specifically LLMs (ChatGPT, Gemini, any AI where a prompt is given to give a response), it has been used to cheat, primarily in school from what I have seen. The bible directly warns of cheating stating “Dishonest money dwindles away, but whoever gathers money little by little makes it grow.” (Proverbs 13:11). Dishonest money can be used as an analogy of cheating, saying money made without using proper routes results in inevitable failure. AI can be seen in the same manner, AI is used to cut corners a lot of the time, making assignments easier or letting AI take the assignment completely. Over time this leads the cheater to cut so many corners that they lose all capacities for learning because AI is so easy to use and cheat with.`}},

  { id:'cmd2', type:'cmd', x:20, y:230, w:182, h:90,
    badge:'You shall not lie', title:'AI deepfakes & fraud',
    sub:'Billions in losses from scams using AI-generated images and voices',
    detail:{ label:'Commandment — Guardrail',
      body:`Of all the commandments this one is heavily impacted by AI, specifically the creation of deepfake images. Deepfake images are images generated by AI typically depicting some sort of figure in real-life, to a degree of realism where many people fall for them without realizing. An example are the deepfake images of real people being used for fraudulent purposes, a NBC news article reported that by 2027 it is estimated that AI deepfakes will cost businesses and consumers $40 billion dollars. An AI researcher from UC Berkeley says that if these trajectories continue AI voices will become nearly indistinguishable from real voices, especially on phone calls where a majority of these scams occur. These issues really demonstrate how dangerous AI has become, especially within these few years, showing how lying becomes ever more prevalent. Through following this commandment we can hope to reduce the use of AI for fraudulent purposes, as researchers like the one here continue to advocate for the tightening of AI deepfakes.`}},

  { id:'cmd3', type:'cmd', x:20, y:372, w:182, h:90,
    badge:'You shall not murder', title:'AI autonomous weapons',
    sub:'Anthropic refused a $200M U.S. military contract, staying true to their values',
    detail:{ label:'Commandment — Guardrail',
      body:`The newest addition to AI are AI weapons, specifically by the U.S. military who have been trying to find a way to integrate AI into warfare. A couple months back, this commandment was shown directly through Anthropic, who fought back against the U.S. government, stating that AI should not be used to kill for military purposes. Anthropic keeps their values by denying the U.S. government and resisting the $200 million contract, drawing the line at autonomous weapons. Anthropic’s values are very much in line with that of this commandment, letting them be a shining model as to how similar values such as this can become guardrails against the dangers of AI.`}},

  { id:'ser1', type:'ser', x:718, y:60,  w:190, h:90,
    badge:'The Golden Rule', title:'ICE deportations',
    sub:'Policies built without empathy for those targeted',
    detail:{ label:'Sermon on the Mount',
      body:`These days many lack the concept of the Golden Rule, especially policy makers who push policies without considering how it may hurt the ones targeted. This can be seen in the ICE deportations, targeting minorities mainly from Latin America, and many times deporting full-fledged American citizens. This policy was not built with the Golden Rule in mind, not considering the feeling of being possibly thrown out of your own country.`}},

  { id:'ser2', type:'ser', x:718, y:192, w:190, h:90,
    badge:'Concerning retaliation', title:'"Alpha" influencer culture',
    sub:'Modern day influencers contradict Catholic teachings by promoting aggression',
    detail:{ label:'Sermon on the Mount',
      body:`In today’s society with the prevalence of “Alpha” male influencers, many young men have been taught that not retaliating is weak and that when you are hit you should hit back harder. This type of teaching is directly against the teachings of the Bible. The Bible teaches to “Turn the other cheek”, instructing one to stand down even if physically attacked, preaching peace and forgiveness rather than continued aggression. `}},

  { id:'ser3', type:'ser', x:718, y:324, w:190, h:90,
    badge:'Judging others', title:'Judgment through social media',
    sub:'Judging others through materialistic comparisons and ill-spirited humor',
    detail:{ label:'Sermon on the Mount',
      body:`Another issue created by social media is comparison, comparing yourself to someone online or someone in real life. This often leads to judging, either criticizing oneself or someone else because you see them as lesser. These types of comparisons are often caused by materialistic matters, such as money, however another type of judgement comes from dark, many times improper, humor. Many shorts platforms, TikTok, Instagram, etc. but mainly Instagram, push “humorous” content mocking or laughing at people with disabilities, creating a very disturbing form of judgement.`}},

  { id:'ser4', type:'ser', x:718, y:456, w:190, h:90,
    badge:'Treasure & worry', title:'Influencer wealth obsession',
    sub:'Flaunting luxury through loans',
    detail:{ label:'Sermon on the Mount', 
      body:`Yet another issue brought up by social media is an overfixation of wealth, seeing these famous influencers flaunting their expensive clothes, cars, etc, leading young people to believe flaunting is what it means to be successful. This leads people to take out loans, and use any sort of method to buy expensive things, because that is their twisted idea of wealth, believing physical appearance to be the only important thing. And due to these crazy loans they end up creating problems and worry.`}},

  { id:'ser5', type:'ser', x:718, y:588, w:190, h:90,
    badge:'Hearers & doers', title:'Academic advice ignored',
    sub:'Receiving every tool for success and choosing not to act',
    detail:{ label:'Sermon on the Mount', 
      body:`From personal experience I see how many people only “hear” advice without acting on them, typically leading to academic consequences. We receive tons of advice and information on how to succeed in school, however there are so many that I know personally who refuse to act on this advice, choosing to just not do the work. However I also know many who act on the advice, and conversely leading to success. `}},

  { id:'ori1', type:'ori', x:80,  y:720, w:205, h:90,
    badge:'Original teaching 1', title:"Ignore the voice that says it's too late",
    sub:'Nothing is too late to start',
    detail:{ label:'Original Teaching', 
      body:`For many there is a voice that says it's too late, that there is a specific window to do something, and anything after is weird or embarrassing. But that voice is all but a sham, why is it too late? Why is it weird? Why is it embarrassing? Most of the time the answers are all self-inflicted and superficial, ultimately meaning nothing. I myself have fallen victim to this mentality many times. If I’m late to basketball practice, why should I even show up? It might be embarrassing. In reality it meant nothing, I showed up to school late multiple times and nothing catastrophic happened. Sure some teachers might be upset if I do it everyday, but in the end it meant very little. Analyzing these voices which tell you to stop because you are too late is like a little devil on your shoulder, preventing you from doing what you actually want. This can reflect faith as well, Catholicism is often introduced as something you are born with through family and a young baptism, especially when I was young, I felt religion is something automatically assigned with conversion to another being heavily frowned upon. The danger is that for those who hold this misconception they believe that it is too late to convert even if they want to. Ignoring the voice which says it’s too late is integral to realize your own faith which you hold deep down, which is being suppressed by the little devil on your shoulder.`}},

  { id:'ori2', type:'ori', x:357, y:720, w:205, h:90,
    badge:'Original teaching 2', title:'Respect the anonymous neighbour',
    sub:'Loving thy neighbour extends to more than just the ones that live by your side',
    detail:{ label:'Original Teaching', 
      body:`Technology allows us to hide our identities, making bullying and saying extremist things a lot easier than in real life. Cyberbullying is a common symptom, because saying things online is largely anonymous, saying offensive and harmful things become easier. These factors allow cyberbullying to become extremely prevalent in today’s day and age, where social media is massive. Research also shows that victims of cyberbullying are 2 times more likely to take their lives than non-bullied individuals. Due to these problems this teaching becomes ever so important, respecting the ones we don’t know could very well save a life. Following this teaching can also bring one closer to God. Respect is one of the most important teachings Catholicism emphasizes, loving thy neighbour, respecting your parents, etc. following this teaching stays true to these core values, in turn becoming closer with God.`}},

  { id:'ori3', type:'ori', x:634, y:720, w:205, h:90,
    badge:'Original teaching 3', title:'Learn to separate from the screen',
    sub:'Screens are becoming an unhealthy addiction for many, especially youth',
    detail:{ label:'Original Teaching', 
      body:`Social media and technology has rewired the way youth today spend their time, with more and more spending time alone on a screen than ever before. With teenagers averaging 8 hours on a screen per day, this becomes extremely alarming as many studies have found that excess screen time actually lowers social skills, and increases likelihood of depression. Youth should learn to separate from their screens, and make more face to face interactions, like playing sports, or just hanging out with friends, as those are proven ways to increase mental health. Being hooked on a device draws you away from the physical world, trapping you in a loop of dopamine. This also deteriorates your connection with God as the screen distracts you. Breaking away from the screen helps to reattach yourself to the real world, to the place where God can be felt the most tangibly.`}},
];

const typeColors = { cmd:'#d06030', ser:'#2070c8', ori:'#20a040' };

function buildMap() {
  const map = document.getElementById('map');
  const svg = document.getElementById('lines');
  svg.innerHTML = '';
  map.querySelectorAll('.node').forEach(el => el.remove());

  const center = nodes.find(n => n.id === 'center');
  const CX = center.x + center.w / 2;
  const CY = center.y + center.h / 2;

  let mapH = 0;
  nodes.forEach(n => { mapH = Math.max(mapH, n.y + n.h + 40); });
  map.style.minHeight = mapH + 'px';

  nodes.forEach(n => {
    const el = document.createElement('div');
    el.className = 'node n-' + n.type + (n.type === 'center' ? ' center' : '');
    el.style.cssText = `left:${n.x}px;top:${n.y}px;width:${n.w}px;min-height:${n.h}px;`;
    let inner = '';
    if (n.badge) inner += `<div class="node-badge">${n.badge}</div>`;
    inner += `<div class="node-title">${n.title}</div>`;
    if (n.sub) inner += `<div class="node-sub">${n.sub}</div>`;
    el.innerHTML = inner;
    if (n.detail) el.onclick = () => openPanel(n);
    map.appendChild(el);

    if (n.type === 'center') return;
    const nx = n.x + n.w / 2;
    const ny = n.y + n.h / 2;
    const color = typeColors[n.type];
    let d;
    if (n.type === 'cmd') {
      const midX = nx + (CX - nx) * 0.5;
      d = `M ${nx} ${ny} C ${midX} ${ny}, ${midX} ${CY}, ${CX} ${CY}`;
    } else if (n.type === 'ser') {
      const midX = CX + (nx - CX) * 0.5;
      d = `M ${CX} ${CY} C ${midX} ${CY}, ${midX} ${ny}, ${nx} ${ny}`;
    } else {
      const midY = ny + (CY - ny) * 0.5;
      d = `M ${nx} ${ny} C ${nx} ${midY}, ${CX} ${midY}, ${CX} ${CY}`;
    }
    const path = document.createElementNS('http://www.w3.org/2000/svg', 'path');
    path.setAttribute('d', d);
    path.setAttribute('stroke', color);
    path.setAttribute('stroke-width', '1.5');
    path.setAttribute('fill', 'none');
    path.setAttribute('opacity', '0.35');
    path.setAttribute('stroke-dasharray', '5 4');
    svg.appendChild(path);
  });
}

function enterMap() {
  document.getElementById('start-screen').style.display = 'none';
  const ms = document.getElementById('map-screen');
  ms.style.display = 'block';
  ms.classList.add('fade-in');
  buildMap();
  applyScale();
}

function goBack() {
  document.getElementById('map-screen').style.display = 'none';
  const ss = document.getElementById('start-screen');
  ss.style.display = 'flex';
  ss.classList.add('fade-in');
}

function openPanel(n) {
  const d = n.detail;
  const cls = { cmd:'pb-cmd', ser:'pb-ser', ori:'pb-ori' }[n.type] || '';
  const pb = document.getElementById('pb');
  pb.textContent = d.label;
  pb.className = 'panel-badge ' + cls;
  document.getElementById('pt').textContent = n.title;
  let html = '';
  html += `<div class="panel-body">${d.body.replace(/\n/g,'<br><br>')}</div>`;
  document.getElementById('pb2').innerHTML = html;
  document.getElementById('panel').classList.add('open');
}

function closePanel() { document.getElementById('panel').classList.remove('open'); }
function handleOverlayClick(e) { if (e.target === document.getElementById('panel')) closePanel(); }

function applyScale() {
  const map = document.getElementById('map');
  const wrap = document.getElementById('canvas-wrap');
  if (!wrap) return;
  const scale = Math.min(1, (wrap.clientWidth - 40) / 920);
  if (scale < 1) {
    map.style.transform = `scale(${scale})`;
    map.style.transformOrigin = 'top center';
    map.style.marginBottom = `-${(1 - scale) * 880}px`;
  } else {
    map.style.transform = '';
    map.style.marginBottom = '';
  }
}

window.addEventListener('resize', applyScale);